### ISSUE TITLE
Packer

### ISSUE THREAD

**Issue by tom99925** [lpiob/MTA-XyzzyRP#260]
Mam pytanie bo się męcze z tym jak dodać funkcje do Packera takie jakie są w DFT żeby mi blokował koła jak ładuje do niego pojazdy?

**Comment by lpiob** [comment]
Packer celowo nie został nigdy oprogramowany, z powodu ograniczeń w GTA:
http://wiki.multitheftauto.com/wiki/AttachElements
Note #2: Due to a limitation in GTA, unexpected attach rotations may occur if all rotation offsets are non-zero. (i.e. Try to ensure at least one of 'xRotOffset', 'yRotOffset' or 'zRotOffset' is zero)

W przypadku pojazdu Packer pojazd jest zawsze pod niezerowymi kątami. Można je odpowiedni przekształcić, ale do tego potrzebna jest zaawansowana matematyka. Ja tego nie potrafię więc nigdy tego nie robiłem.

**Comment by tom99925** [comment]
Dlatego nie umiałem ustawić żeby pojazd stał nad nim a nie pod nim ok dzieki za odp
